### ISSUE TITLE
SFX: Looping Bug

### ISSUE THREAD

**Issue by Leonard-McCoy** [NagyD/SDLPoP#170] opened 2018-04-01 15:35 UTC
Whenever a guard attacks with his sword and whiffs while Kid's switching screens the sound effect of the attack keeps looping indefinitely until Kid re-enters the screen where the guard is located at.

How to reproduce:
1. Do the trick in level 1 where you skip getting the sword, that is, lure the guard watching over the exit to the edge of the screen and exit the screen in the instance the guard is swinging at you. He misses the swing while you're switching screens.
3. Observe result (sound effect of sword attack keeps repeating indefinitely).

**Comment by Falcury** [comment] 2018-04-02 13:02
I have also experienced this sometimes, though not necessarily at the same spot. It indeed seemed to happen when exiting the room at the exact moment when a guard swings the sword but misses.
I am not 100% sure, but it is possible that the original DOS version also has this bug.
Maybe it would be helpful to have a recorded replay where this occurs. Then we might be able to track down the cause more easily.

**Comment by Leonard-McCoy** [comment] 2018-04-02 18:32
I don't remember this  happen in the DOS version which is why I was so surprised it happened in SDLPoP. I'll get a replay, no problem.

**Comment by EndeavourAccuracy** [comment] 2018-04-04 14:46
> I don't remember this happen in the DOS version, neither on
> original hardware nor emulated via DOSBox.

I do remember seeing it with DOS(Box).
At 4:18 and 4:23 in [this recording](https://www.youtube.com/watch?v=U-P2-7OFQAY&t=257) of level 1 of _The Deserts of Persia_.
Doesn't use SDLPoP. The guard's attack is at 4:09.

**Comment by NagyD** [comment] 2018-04-07 07:13
Here is the code that plays this sound: https://github.com/NagyD/SDLPoP/blob/master/src/seg002.c#L994
The problem is that nothing checks here (or in the caller functions) whether there is actually a guard in the current room.
Also, when the prince leaves the guard's room, most the guard's info is kept, except that its direction is set to "none".

And yes, I could reproduce this now in DOSBox.
I tried to upload a video, but GitHub just won't accept this ZIP file.

**Comment by NagyD** [comment] 2018-04-07 07:15
Here is my fix: 0f75fb430a5e93db2f6a2855f080c15a4de0c423
It fixes the bug for me, please test if it also works for you.

**Comment by EndeavourAccuracy** [comment] 2018-04-12 23:08
I've tested master with the replay file provided by Leonard-McCoy, and the bug appears to be fixed.

**Comment by NagyD** [comment] 2018-04-14 12:39
Then I'm closing this.

**Closed by NagyD** 2018-04-14 12:39 UTC
