### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by agustin87** [NagyD/SDLPoP#151] opened 2017-12-24 00:24 UTC
https://youtu.be/oorL0r_dAks

**Comment by NagyD** [comment] 2017-12-31 18:10
I watched your video, but I don't see any bugs.
Please explain what the problem is.

**Comment by agustin87** [comment] 2017-12-31 19:45
spanish:
- primero: el guardia no debe abandonar su posisión
- segundo: en el nivel 2 el príncipe saca la espada que no agarró en el nivel 1

( google translate )

- first: the guard must not abandon his position
- second: at level 2 the prince draws the sword he did not grab at level 1

**Comment by NagyD** [comment] 2018-01-06 07:53
This is also possible in the original game: See [this page](http://popuw.com/tips.html), under "Pass first level without taking the sword and fighting guards".

In fact, this shortcut is even included in [the official strategy guide](http://popuw.com/story/pop-01.html), as "The Short Version".

Therefore, I'd say that this is not a bug that should be fixed.

**Closed by NagyD** 2018-01-06 07:53 UTC
