### ISSUE TITLE
Pixel Perfect screen scaling

### ISSUE THREAD

**Issue by Clovergruff** [NagyD/SDLPoP#147] opened 2017-11-17 16:43 UTC
Hi!

I'd like to request a feature/option for rendering the game in such a way that would provide consistent pixel sizes on the screen. This may not be obvious or visible to a lot of people, but that's how the game is supposed to look like.

If you look at some dithered checkerboard-like areas, you can see how the pixels are actually different sizes:
![nonpixelperfect](https://user-images.githubusercontent.com/5364721/32958719-fea1cdf6-cbc7-11e7-8eab-49bb4fb50bae.png)

But they should all be the same size:
![pixelperfect](https://user-images.githubusercontent.com/5364721/32958722-018a1c3a-cbc8-11e7-9e71-d19ccf7a8e89.png)

Here's a direct comparison:
![versus](https://user-images.githubusercontent.com/5364721/32958316-c06b8302-cbc6-11e7-9bc2-424871a9707f.png)

There's a modified version of Dosbox that supports this feature. I assume it can be used for a reference in case if this feature would be considered!
Link here: [https://github.com/bladeSk/DOSBox-pixel-perfect](url)

**Comment by NagyD** [comment] 2017-11-19 08:09
It seems that SDL has a function for exactly this: https://wiki.libsdl.org/SDL_RenderSetIntegerScale

**Comment by NagyD** [comment] 2017-11-19 09:28
Here is my implementation on a new branch: https://github.com/NagyD/SDLPoP/commits/integer_scaling
You need to enable this in SDLPoP.ini, the option is called `use_integer_scaling`.
Please try it.

TODO: What to do if 4:3 aspect ratio is also enabled? Currently the game window stays black.
(I added a warning to the INI, and you also get a warning on the console if you enable both settings.)

This happens due to how the 4:3 aspect ratio is implemented: The screen is first scaled to a *very big* size that has the correct aspect ratio and its coordinates are integer multiples of 320×200 (namely: 320 * 5 × 200 * 6 = 1600 × 1200), and then that is scaled down to the current size of the window.
This is bigger than the biggest possible size of the window (i.e. full screen), so the only suitable integer scaling factor is zero.

The same thing happens if you don't enable 4:3 aspect ratio, but resize the window to a size smaller than 320×200.

**Comment by Falcury** [comment] 2017-11-19 12:16
I justed tested it. It works well.
I think the integer scaling should probably be suppressed while the window size is smaller than the logical render size.
I suppose that people with 1440p monitors will be able to use both features together.

**Comment by NagyD** [comment] 2017-11-25 14:43
> I think the integer scaling should probably be suppressed while the window size is smaller than the logical render size.

Done.

> I suppose that people with 1440p monitors will be able to use both features together.

Probably. I added a note to SDLPoP.ini, saying that at least 1600 × 1200 is needed in that case.
(On my system, the maximum resolution is 1440 × 900.)

**Comment by NagyD** [comment] 2017-12-02 11:11
So, can I close the issue and merge the branch?

**Comment by Falcury** [comment] 2017-12-02 14:26
Maybe people will have trouble compiling/running if they are not yet on SDL 2.0.5, like Norbert mentioned here:
http://forum.princed.org/viewtopic.php?f=126&t=4061#p22226

I suppose a compile time check will be sufficient for letting people still compile on older versions.
Something like:
```
#if SDL_VERSION_ATLEAST(2,0,5)
...
#endif
```

The only remaining problem would be if people on Linux having SDL 2.0.4 or lower try to run a pre-built binary. (They would have to recompile using their own installed pre-2.0.5 version of SDL, otherwise the game will probably complain that the procedure entry point SDL_RenderSetIntegerScale could not be located in the dynamic link library.)

**Comment by NagyD** [comment] 2017-12-15 08:50
> I suppose a compile time check will be sufficient for letting people compile on older versions.

Done: ed86fd4922ac285b984c7f9b8a1d0b1721a5954e

> The only remaining problem would be if people on GNU/Linux having SDL 2.0.4 or lower try to run a pre-built binary.

We could use [dlopen+dlsym](https://linux.die.net/man/3/dlopen) on GNU/Linux (and [LoadLibrary](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684175(v=vs.85).aspx)+[GetProcAddress](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683212(v=vs.85).aspx) on Windows).
But that seems to be overkill...
And anyway, we are not distributing pre-built SDLPoP binaries for GNU/Linux. (Or are we?)

So, can I merge this into master, or are there still problems?

**Comment by EndeavourAccuracy** [comment] 2017-12-15 18:16
>  And anyway, we are not distributing pre-built SDLPoP binaries for GNU/Linux. (Or are we?)

All the ZIP packages [at popot.org](https://www.popot.org/get_the_games.php?game=SDLPoP) have 64-bit ELF executables.
Compiled and added by me to make the package even end-user-friendlier.
(Of course, everyone is free to compile their own instead.)

**Comment by NagyD** [comment] 2017-12-18 19:25
> All the ZIP packages at popot.org have 64-bit ELF executables.
> Compiled and added by me to make the package even end-user-friendlier.

Oh, sorry, I didn't know about that.
(But I at least asked "are we?". :) )

However, if you compile those with SDL 2.0.4 as you wrote [here](http://forum.princed.org/viewtopic.php?p=22226#p22226), then we don't have to worry about the problem with SDL_RenderSetIntegerScale outlined by Falcury.
Instead, the integer scaling will be simply disabled, with a warning that tells to recompile with SDL 2.0.5 to enable it.

So, can I merge now?

**Comment by Shane32** [comment] 2018-01-05 04:17
I use dosbox in a configuration where it doubles the 320x200 to 640x400, then does a "smooth" scaling of the 640x400 output to the native resolution of the monitor (with aspect correction so it maintains the correct ratio).  I find this gives both the most pleasant and authentic representation of a 1990-era computer, _because_ the pixels are just a bit fuzzy.  Note that I think this is done by DosBox via "hardware scaling" with either opengl or direct3d, as it doesn't work in the other output modes.

**Comment by NagyD** [comment] 2018-01-06 08:53
@Shane32: Here is my first attempt on a new branch: 9c9d2ade021a95bc109de5e9696c5926a934067a
Please try it.

(BTW, I think this should be a separate issue.)

**Comment by Falcury** [comment] 2018-01-13 16:30
>@Shane32: Here is my first attempt on a new branch: 9c9d2ad
> Please try it.
I tried it. One issue I found: you can sometimes see vertical 'lines' on the left and right edges of the room. This happens especially in fullscreen mode. See for example level 2, or level 12, where this can be clearly seen.

**Comment by NagyD** [comment] 2018-01-14 16:52
Yes, I'm seeing something similar.
It seems that each edge of the screen wraps around to the other side.
If I move the prince to the edge and make him turn around, then the "line" on the other edge will move together with the prince.

(I wanted to attach a screenshot, but GitHub gave me an error.)

The good thing: This is a known SDL bug: https://bugzilla.libsdl.org/show_bug.cgi?id=1878
A patch was made in 2013, and it was finally accepted in 2017 December.

**Comment by NagyD** [comment] 2018-01-21 16:18
I added an INI option to change the scaling mode: 36635f699baf96e596b664446eb0bb24a8a47fdf
This way you can switch between sharp and fuzzy pixels.

**Comment by NagyD** [comment] 2018-02-03 15:26
@Falcury, do you think I can merge this to master?

**Comment by Falcury** [comment] 2018-02-03 21:17
Yes, I think so!
Will you make fuzzy pixels and 4:3 scaling the new default? (Seeing as they are changed in SDLPoP.ini)

> A patch was made in 2013, and it was finally accepted in 2017 December.

I tested it with the latest version from here:
https://github.com/SDL-mirror/SDL

And it indeed looks like the issue is fixed. Then, I also think it would be a good idea to package a newer SDL2.dll with the release that doesn't have the bug.

I also integrated the fuzzy pixels feature into the menu branch: 
https://github.com/Falcury/SDLPoP/commit/28222e6be07010dcf940cb2bf2f1d96256dede0e

**Comment by NagyD** [comment] 2018-02-04 07:57
> Yes, I think so!

Right, I merged it: 4fd76bc8a5a6c5672166c97eb95403e52eeb1bd4

> Will you make fuzzy pixels and 4:3 scaling the new default? (Seeing as they are changed in SDLPoP.ini)

No, I did that only to "show off" the feature on the separate branch.
I reverted INI settings to default now: 4fd76bc8a5a6c5672166c97eb95403e52eeb1bd4

> Then, I also think it would be a good idea to package a newer SDL2.dll with the release that doesn't have the bug.

Do you mean [your custom-compiled SDL2.dll](http://forum.princed.org/viewtopic.php?p=22517#p22517)?

**Closed by NagyD** 2018-02-04 07:57 UTC

**Comment by Falcury** [comment] 2018-02-04 09:39
> Do you mean your custom-compiled SDL2.dll?

For example, yes.
Although if fuzzy pixels is not the default, then I think it's not as much of a problem (more a minor annoyance for the people that want to use the feature). You could just use SDL 2.0.7, if you feel it's better to stick to the stable SDL2 releases.
